////////////////// prefix wara
const Discord = require("discord.js");
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();

  }
});
j

});

//////////////// tokn lera da bne

mortal.login("OTQyNTEwNjU4MDEwODkwMjYy.YgouXQ.0AEwUciJjrD3oYhetG74ZPuG8go");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");

