////////////////// prefix wara
const Discord = require("discord.js");
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();

  }
});
j

});

//////////////// tokn lera da bne

mortal.login("ODkxMjg3NTU4MDE1ODI3OTc4.Ygi4jw.tJK7dg7APyUcRZWxIp_ZTKAKNEs");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");

