////////////////// prefix wara
const Discord = require("discord.js");
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();
const mortal = new Discord.Client();

  }
});
j

});

//////////////// tokn lera da bne

mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");
mortal.login("");

